CREATE TABLE `configuracaoBoleto` (
	`id` int AUTO_INCREMENT NOT NULL,
	`condominioId` int NOT NULL,
	`banco` varchar(10) NOT NULL DEFAULT '208',
	`nomeBanco` varchar(50) NOT NULL DEFAULT 'BTG PACTUAL',
	`agencia` varchar(10) NOT NULL DEFAULT '0001',
	`digitoAgencia` varchar(2) NOT NULL DEFAULT '0',
	`conta` varchar(20) NOT NULL,
	`digitoConta` varchar(2) NOT NULL DEFAULT '0',
	`convenio` varchar(30) NOT NULL DEFAULT '',
	`ativo` int NOT NULL DEFAULT 1,
	`contaRepasse` int NOT NULL DEFAULT 0,
	`minimosDiasAntesVencimento` int NOT NULL DEFAULT 0,
	`usarMinimoDias` int NOT NULL DEFAULT 0,
	`enviarParcelasApenasPrimeiraPaga` int NOT NULL DEFAULT 0,
	`enviarParcelasApenasAnteriorPaga` int NOT NULL DEFAULT 1,
	`carteira` varchar(5) NOT NULL DEFAULT '1',
	`especieDocumento` varchar(5) NOT NULL DEFAULT 'DD',
	`aceite` varchar(1) NOT NULL DEFAULT 'N',
	`nomeBeneficiario` varchar(100),
	`cnpjBeneficiario` varchar(18),
	`enderecoBeneficiario` varchar(200),
	`localPagamento` varchar(500) NOT NULL DEFAULT 'PAGAVEL EM QUALQUER BANCO ATE O VENCIMENTO',
	`instrucoesCaixa` varchar(500) NOT NULL DEFAULT 'APOS VENCIMENTO COBRAR MULTA DE #MULTA# e MORA DIARIA DE #JUROS#',
	`taxaJurosDia` varchar(10) NOT NULL DEFAULT '0.03330',
	`taxaMulta` varchar(10) NOT NULL DEFAULT '2.00',
	`numeroSequencialArquivo` int NOT NULL DEFAULT 1,
	`padraoNomeArquivo` varchar(100) NOT NULL DEFAULT 'BTG_ddmmyyyy.txt',
	`layoutArquivo` varchar(20) NOT NULL DEFAULT 'CNAB240',
	`enviarInstrucoesProtesto` int NOT NULL DEFAULT 0,
	`habilitarBoleto` int NOT NULL DEFAULT 1,
	`habilitarPix` int NOT NULL DEFAULT 1,
	`taxaCobrancaValor` varchar(15) NOT NULL DEFAULT '3.50',
	`taxaCobrancaPercentual` varchar(10) NOT NULL DEFAULT '0.00',
	`despesaValor` varchar(15) NOT NULL DEFAULT '0.00',
	`despesaPercentual` varchar(10) NOT NULL DEFAULT '0.00',
	`nossoNumeroAtual` int NOT NULL DEFAULT 1000000001,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `configuracaoBoleto_id` PRIMARY KEY(`id`),
	CONSTRAINT `configuracaoBoleto_condominioId_unique` UNIQUE(`condominioId`)
);
