CREATE TABLE `auditLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`userName` varchar(255),
	`userRole` varchar(50),
	`userEmail` varchar(255),
	`action` varchar(100) NOT NULL,
	`entity` varchar(100),
	`entityId` varchar(100),
	`entityLabel` varchar(255),
	`condominioId` int,
	`condominioNome` varchar(255),
	`beforeData` text,
	`afterData` text,
	`metadata` text,
	`ipAddress` varchar(45) NOT NULL DEFAULT 'unknown',
	`userAgent` varchar(500),
	`sessionId` varchar(100),
	`severity` enum('info','warning','critical') NOT NULL DEFAULT 'info',
	`success` tinyint NOT NULL DEFAULT 1,
	`errorMessage` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `auditLogs_id` PRIMARY KEY(`id`)
);
